---
# tasks file for nodejs

- name: Load meta vars
  include_vars:
      file: meta/main.yml
      name: meta

- name: Assertions
  assert:
    that:
        - ansible_distribution in meta.galaxy_info.platforms|map(attribute='name')
        - |
            (meta.galaxy_info.platforms|selectattr('name', 'equalto', ansible_distribution)|first).versions|intersect([ansible_distribution_release, ansible_distribution_version])|length > 0
        - nodejs_version in [6, 8]

- name: APT install prerequisites
  apt:
      name: apt-transport-https
      state: present
      update_cache: True
      cache_valid_time: 3600

- name: Add APT repository key
  apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present

- name: Add APT repository
  apt_repository:
      repo: |
          deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_lsb.codename }} main
      state: present
      update_cache: True

- name: APT install
  apt:
      name: nodejs
      state: present
      update_cache: True
      cache_valid_time: 3600
